---
title: "SPRINT_SPEED_FIGURES"
author: "Daniel Ritchie"
date: "2025-03-10"
output: html_document
---


```{r}

library(dplyr)
library(tidyverse)
library(ggplot2)
library(lme4)
library(dplyr)
library(rptR)
library(lmPerm)
library(nls.multstart)
library(purrr)
library(rTPC)
library(broom)
library(ggrepel)
```



## Calculate for PopX treatment 
```{r}
# Group data by Pop × Treatment instead of ID
d_fits_grouped <- data.rtpc %>%
  group_by(Pop, Treatment) %>%
  nest() %>%
  mutate(boatman = map(data, ~nls_multstart(
    fastest_25cm ~ boatman_2017(temp = Body_temp, rmax, tmin, tmax, a, b),
    data = .x,
    iter = c(4,4,4,4,4),
    start_lower = get_start_vals(.x$Body_temp, .x$fastest_25cm, model_name = 'boatman_2017') - 10,
    start_upper = get_start_vals(.x$Body_temp, .x$fastest_25cm, model_name = 'boatman_2017') + 10,
    lower = get_lower_lims(.x$Body_temp, .x$fastest_25cm, model_name = 'boatman_2017'),
    upper = get_upper_lims(.x$Body_temp, .x$fastest_25cm, model_name = 'boatman_2017'),
    supp_errors = 'Y',
    convergence_count = FALSE)))

# Get predictions per Pop × Treatment
d_preds_grouped <- d_fits_grouped %>%
  mutate(new_data = map(data, ~tibble(Body_temp = seq(min(.x$Body_temp), max(.x$Body_temp), length.out = 1000)))) %>%
  select(-data) %>%
  mutate(preds = map2(boatman, new_data, ~broom::augment(.x, new_data = .y))) %>%
  unnest(preds)

# Bootstrap confidence intervals
# get coefs
d_fits_grouped <- mutate(d_fits_grouped, coefs = map(boatman, coef))
library(minpack.lm)
# fit with nlsLM instead

d_fits_grouped <- mutate(d_fits_grouped, nls_fit = map2(data, coefs, ~nlsLM(fastest_25cm ~ boatman_2017(Body_temp, rmax, tmin, tmax, a,b),
                                        data = .x,
                                        start = .y,
                                        lower = get_lower_lims(.x$Body_temp, .x$fastest_25cm,  model_name = 'boatman_2017'),
                                        upper = get_upper_lims(.x$Body_temp, .x$fastest_25cm,  model_name = 'boatman_2017'))))

head(d_fits_grouped)

d_fits_grouped$nls_fit[[1]]

library(car)
# create empty list column
library(minpack.lm)
d_fits_grouped <- mutate(d_fits_grouped, bootstrap = list(rep(NA, n())))

# run for loop to bootstrap each refitted model
for(i in 1:nrow(d_fits_grouped)){
  temp_data_grouped <- d_fits_grouped$data[[i]]
  temp_fits_grouped <- minpack.lm::nlsLM(fastest_25cm ~ 'boatman_2017'(Body_temp, rmax, tmin, tmax, a,b),
               data = temp_data_grouped,
               start = d_fits_grouped$coefs[[i]],
               lower = get_lower_lims(temp_data_grouped$Body_temp, temp_data_grouped$fastest_25cm, model_name = 'boatman_2017'),
               upper = get_upper_lims(temp_data_grouped$Body_temp, temp_data_grouped$fastest_25cm, model_name = 'boatman_2017'))
  boot <- Boot(temp_fits_grouped, method = 'residual')
  d_fits_grouped$bootstrap[[i]] <- boot
  rm(list = c('temp_fit', 'temp_data', 'boot'))
}

d_fits_grouped


# get the raw values of each bootstrap
d_fits_grouped <- mutate(d_fits_grouped, output_boot = map(bootstrap, function(x) x$t))



# calculate predictions with a gnarly written function
d_fits_grouped <- mutate(d_fits_grouped, preds = map2(output_boot, data, function(x, y){
  temp <- as.data.frame(x) %>%
    drop_na() %>%
    mutate(iter = 1:n()) %>%
    group_by_all() %>%
    do(data.frame(Body_temp = seq(min(y$Body_temp), max(y$Body_temp), length.out = 1000))) %>%
    ungroup() %>%
    mutate(pred ='boatman_2017'(Body_temp, rmax, tmin, tmax, a,b))
  return(temp)
}))

# select, unnest and calculate 95% CIs of predictions
boot_conf_preds_grouped <- select(d_fits_grouped, preds) %>%
  unnest(preds) %>%
  group_by(Body_temp, Pop, Treatment) %>%
  summarise(conf_lower = quantile(pred, 0.025, na.rm = TRUE),
            conf_upper = quantile(pred, 0.975, na.rm = TRUE),
            .groups = 'drop')

fastest_paramsd_fits_grouped <- pivot_longer(d_fits_grouped, names_to = 'model_name', values_to = 'fit', boatman) %>%
  mutate(params = map(fit, calc_params)) %>%
  select(Pop, Treatment, model_name,  params) %>%
  unnest(params)
```


```{r}
# Define new population names
pop_names <- c("STURT" = "Sturt National Park",
               "MR" = "Muloorina Station",
               "KNGA" = "Kinchega National Park", 
               "NGKT" = "Ngarkat Cons. Park")

# Apply new names & order
data.rtpc <- data.rtpc %>%
  mutate(Pop = factor(as.character(Pop),  # Ensure it's treated as a character first
                      levels = c("STURT", "MR", "KNGA", "NGKT"),  # Set order
                      labels = pop_names))  # Rename

d_preds_grouped <- d_preds_grouped %>%
  mutate(Pop = factor(as.character(Pop), levels = c("STURT", "MR", "KNGA", "NGKT"), labels = pop_names))

boot_conf_preds_grouped <- boot_conf_preds_grouped %>%
  mutate(Pop = factor(as.character(Pop), levels = c("STURT", "MR", "KNGA", "NGKT"), labels = pop_names))
```


```{r}
TPC_boatman <- ggplot(data.rtpc, aes(x = Body_temp, y = fastest_25cm, 
                                     color = interaction(Pop, Treatment), 
                                     shape = interaction(Pop, Treatment))) +
  geom_point(alpha = 0.7, size = 2) +

  # Add Boatman-fitted curves
  geom_line(data = d_preds_grouped, aes(x = Body_temp, y = .fitted, 
                                        color = interaction(Pop, Treatment)), 
            size = 1.5) +

  # Add confidence intervals
  geom_ribbon(data = boot_conf_preds_grouped, aes(x = Body_temp, ymin = conf_lower, ymax = conf_upper, 
                                          fill = interaction(Pop, Treatment)), 
             alpha = 0.2, inherit.aes = FALSE) +

  scale_color_manual(values = c("darkblue", "darkred", "lightblue", "darkgreen", "purple", "orange", "brown", "pink")) +  
  scale_fill_manual(values = c("darkblue", "darkred", "lightblue", "darkgreen", "purple", "orange", "brown", "pink")) +  
  scale_shape_manual(values = c(16, 17, 18, 19, 15, 7, 8, 10)) +  

  theme_bw() +
  ylim(-0.5, 4) +
  facet_wrap(~Pop) +
  theme_classic() +
  labs(x = "Temperature (°C)", 
       y = "Maximum Sprint Speed 0.25m (m/s)", 
       color = "Pop-Treatment", 
       shape = "Pop-Treatment", 
       fill = "Pop-Treatment")

TPC_boatman


```











## Calculate for Pop
```{r}

# Group data by Pop × Treatment instead of ID
d_fits_grouped <- data.rtpc %>%
  group_by(Pop) %>%
  nest() %>%
  mutate(boatman = map(data, ~nls_multstart(
    fastest_25cm ~ boatman_2017(temp = Body_temp, rmax, tmin, tmax, a, b),
    data = .x,
    iter = c(4,4,4,4,4),
    start_lower = get_start_vals(.x$Body_temp, .x$fastest_25cm, model_name = 'boatman_2017') - 10,
    start_upper = get_start_vals(.x$Body_temp, .x$fastest_25cm, model_name = 'boatman_2017') + 10,
    lower = get_lower_lims(.x$Body_temp, .x$fastest_25cm, model_name = 'boatman_2017'),
    upper = get_upper_lims(.x$Body_temp, .x$fastest_25cm, model_name = 'boatman_2017'),
    supp_errors = 'Y',
    convergence_count = FALSE)))

# Get predictions per Pop × Treatment
d_preds_grouped <- d_fits_grouped %>%
  mutate(new_data = map(data, ~tibble(Body_temp = seq(min(.x$Body_temp), max(.x$Body_temp), length.out = 1000)))) %>%
  select(-data) %>%
  mutate(preds = map2(boatman, new_data, ~broom::augment(.x, new_data = .y))) %>%
  unnest(preds)

# Bootstrap confidence intervals
# get coefs
d_fits_grouped <- mutate(d_fits_grouped, coefs = map(boatman, coef))
library(minpack.lm)
# fit with nlsLM instead

d_fits_grouped <- mutate(d_fits_grouped, nls_fit = map2(data, coefs, ~nlsLM(fastest_25cm ~ boatman_2017(Body_temp, rmax, tmin, tmax, a,b),
                                        data = .x,
                                        start = .y,
                                        lower = get_lower_lims(.x$Body_temp, .x$fastest_25cm,  model_name = 'boatman_2017'),
                                        upper = get_upper_lims(.x$Body_temp, .x$fastest_25cm,  model_name = 'boatman_2017'))))

head(d_fits_grouped)

d_fits_grouped$nls_fit[[1]]

library(car)
# create empty list column
library(minpack.lm)
d_fits_grouped <- mutate(d_fits_grouped, bootstrap = list(rep(NA, n())))

# run for loop to bootstrap each refitted model
for(i in 1:nrow(d_fits_grouped)){
  temp_data_grouped <- d_fits_grouped$data[[i]]
  temp_fits_grouped <- minpack.lm::nlsLM(fastest_25cm ~ 'boatman_2017'(Body_temp, rmax, tmin, tmax, a,b),
               data = temp_data_grouped,
               start = d_fits_grouped$coefs[[i]],
               lower = get_lower_lims(temp_data_grouped$Body_temp, temp_data_grouped$fastest_25cm, model_name = 'boatman_2017'),
               upper = get_upper_lims(temp_data_grouped$Body_temp, temp_data_grouped$fastest_25cm, model_name = 'boatman_2017'))
  boot <- Boot(temp_fits_grouped, method = 'residual')
  d_fits_grouped$bootstrap[[i]] <- boot
  rm(list = c('temp_fit', 'temp_data', 'boot'))
}

d_fits_grouped


# get the raw values of each bootstrap
d_fits_grouped <- mutate(d_fits_grouped, output_boot = map(bootstrap, function(x) x$t))



# calculate predictions with a gnarly written function
d_fits_grouped <- mutate(d_fits_grouped, preds = map2(output_boot, data, function(x, y){
  temp <- as.data.frame(x) %>%
    drop_na() %>%
    mutate(iter = 1:n()) %>%
    group_by_all() %>%
    do(data.frame(Body_temp = seq(min(y$Body_temp), max(y$Body_temp), length.out = 1000))) %>%
    ungroup() %>%
    mutate(pred ='boatman_2017'(Body_temp, rmax, tmin, tmax, a,b))
  return(temp)
}))

# select, unnest and calculate 95% CIs of predictions
boot_conf_preds_grouped <- select(d_fits_grouped, preds) %>%
  unnest(preds) %>%
  group_by(Body_temp, Pop) %>%
  summarise(conf_lower = quantile(pred, 0.025, na.rm = TRUE),
            conf_upper = quantile(pred, 0.975, na.rm = TRUE),
            .groups = 'drop')

fastest_paramsd_fits_grouped <- pivot_longer(d_fits_grouped, names_to = 'model_name', values_to = 'fit', boatman) %>%
  mutate(params = map(fit, calc_params)) %>%
  select(Pop, model_name,  params) %>%
  unnest(params)
```


```{r}
# Define new population names
pop_names <- c("STURT" = "Sturt National Park",
               "MR" = "Muloorina Station",
               "KNGA" = "Kinchega National Park", 
               "NGKT" = "Ngarkat Cons. Park")

# Apply new names & order
data.rtpc <- data.rtpc %>%
  mutate(Pop = factor(as.character(Pop),  # Ensure it's treated as a character first
                      levels = c("STURT", "MR", "KNGA", "NGKT"),  # Set order
                      labels = pop_names))  # Rename

d_preds_grouped <- d_preds_grouped %>%
  mutate(Pop = factor(as.character(Pop), levels = c("STURT", "MR", "KNGA", "NGKT"), labels = pop_names))

boot_conf_preds_grouped <- boot_conf_preds_grouped %>%
  mutate(Pop = factor(as.character(Pop), levels = c("STURT", "MR", "KNGA", "NGKT"), labels = pop_names))
```


```{r}
TPC_boatman_pop <- ggplot(data.rtpc, aes(x = Body_temp, y = fastest_25cm, 
                                         color = Pop, 
                                         shape = Pop)) +  # Fixed closing parenthesis
  geom_point(alpha = 0.7, size = 2) +

  # Add Boatman-fitted curves
  geom_line(data = d_preds_grouped, aes(x = Body_temp, y = .fitted, 
                                        color = Pop), 
            size = 1.5) +

  # Add confidence intervals
  geom_ribbon(data = boot_conf_preds_grouped, aes(x = Body_temp, ymin = conf_lower, ymax = conf_upper, 
                                                  fill = Pop), 
              alpha = 0.2, inherit.aes = FALSE) +

  scale_color_manual(values = c("darkblue", "darkred", "lightblue", "darkgreen", 
                                "purple", "orange", "brown", "pink")) +  
  scale_fill_manual(values = c("darkblue", "darkred", "lightblue", "darkgreen", 
                               "purple", "orange", "brown", "pink")) +  
  scale_shape_manual(values = c(16, 17, 18, 19, 15, 7, 8, 10)) +  

  theme_bw() +
  ylim(-0.5, 4) +
  theme_classic() +
  labs(x = "Temperature (°C)", 
       y = "Maximum Sprint Speed 0.25m (m/s)", 
       color = "Pop", 
       shape = "Pop", 
       fill = "Pop")

TPC_boatman_pop

```

```{r}
ggsave("~/Desktop/phd/Documents/Chapter_1_Honours/TELO.tiff", TPC_boatman_pop, width = 7.5, height = 4, dpi = 300)
```






## Calculate for Treatment
```{r}

# Group data by Pop × Treatment instead of ID
d_fits_grouped <- data.rtpc %>%
  group_by(Treatment) %>%
  nest() %>%
  mutate(boatman = map(data, ~nls_multstart(
    fastest_25cm ~ boatman_2017(temp = Body_temp, rmax, tmin, tmax, a, b),
    data = .x,
    iter = c(4,4,4,4,4),
    start_lower = get_start_vals(.x$Body_temp, .x$fastest_25cm, model_name = 'boatman_2017') - 10,
    start_upper = get_start_vals(.x$Body_temp, .x$fastest_25cm, model_name = 'boatman_2017') + 10,
    lower = get_lower_lims(.x$Body_temp, .x$fastest_25cm, model_name = 'boatman_2017'),
    upper = get_upper_lims(.x$Body_temp, .x$fastest_25cm, model_name = 'boatman_2017'),
    supp_errors = 'Y',
    convergence_count = FALSE)))

# Get predictions per Pop × Treatment
d_preds_grouped <- d_fits_grouped %>%
  mutate(new_data = map(data, ~tibble(Body_temp = seq(min(.x$Body_temp), max(.x$Body_temp), length.out = 1000)))) %>%
  select(-data) %>%
  mutate(preds = map2(boatman, new_data, ~broom::augment(.x, new_data = .y))) %>%
  unnest(preds)

# Bootstrap confidence intervals
# get coefs
d_fits_grouped <- mutate(d_fits_grouped, coefs = map(boatman, coef))
library(minpack.lm)
# fit with nlsLM instead

d_fits_grouped <- mutate(d_fits_grouped, nls_fit = map2(data, coefs, ~nlsLM(fastest_25cm ~ boatman_2017(Body_temp, rmax, tmin, tmax, a,b),
                                        data = .x,
                                        start = .y,
                                        lower = get_lower_lims(.x$Body_temp, .x$fastest_25cm,  model_name = 'boatman_2017'),
                                        upper = get_upper_lims(.x$Body_temp, .x$fastest_25cm,  model_name = 'boatman_2017'))))

head(d_fits_grouped)

d_fits_grouped$nls_fit[[1]]

library(car)
# create empty list column
library(minpack.lm)
d_fits_grouped <- mutate(d_fits_grouped, bootstrap = list(rep(NA, n())))

# run for loop to bootstrap each refitted model
for(i in 1:nrow(d_fits_grouped)){
  temp_data_grouped <- d_fits_grouped$data[[i]]
  temp_fits_grouped <- minpack.lm::nlsLM(fastest_25cm ~ 'boatman_2017'(Body_temp, rmax, tmin, tmax, a,b),
               data = temp_data_grouped,
               start = d_fits_grouped$coefs[[i]],
               lower = get_lower_lims(temp_data_grouped$Body_temp, temp_data_grouped$fastest_25cm, model_name = 'boatman_2017'),
               upper = get_upper_lims(temp_data_grouped$Body_temp, temp_data_grouped$fastest_25cm, model_name = 'boatman_2017'))
  boot <- Boot(temp_fits_grouped, method = 'residual')
  d_fits_grouped$bootstrap[[i]] <- boot
  rm(list = c('temp_fit', 'temp_data', 'boot'))
}

d_fits_grouped


# get the raw values of each bootstrap
d_fits_grouped <- mutate(d_fits_grouped, output_boot = map(bootstrap, function(x) x$t))



# calculate predictions with a gnarly written function
d_fits_grouped <- mutate(d_fits_grouped, preds = map2(output_boot, data, function(x, y){
  temp <- as.data.frame(x) %>%
    drop_na() %>%
    mutate(iter = 1:n()) %>%
    group_by_all() %>%
    do(data.frame(Body_temp = seq(min(y$Body_temp), max(y$Body_temp), length.out = 1000))) %>%
    ungroup() %>%
    mutate(pred ='boatman_2017'(Body_temp, rmax, tmin, tmax, a,b))
  return(temp)
}))

# select, unnest and calculate 95% CIs of predictions
boot_conf_preds_grouped <- select(d_fits_grouped, preds) %>%
  unnest(preds) %>%
  group_by(Body_temp, Treatment) %>%
  summarise(conf_lower = quantile(pred, 0.025, na.rm = TRUE),
            conf_upper = quantile(pred, 0.975, na.rm = TRUE),
            .groups = 'drop')

fastest_paramsd_fits_grouped <- pivot_longer(d_fits_grouped, names_to = 'model_name', values_to = 'fit', boatman) %>%
  mutate(params = map(fit, calc_params)) %>%
  select(Treatment, model_name,  params) %>%
  unnest(params)
```





```{r}
TPC_boatman_treat <- ggplot(data.rtpc, aes(x = Body_temp, y = fastest_25cm, 
                                         color = Treatment, 
                                         shape =  Treatment)) +  # Fixed closing parenthesis
  geom_point(alpha = 0.7, size = 2) +

  # Add Boatman-fitted curves
  geom_line(data = d_preds_grouped, aes(x = Body_temp, y = .fitted, 
                                        color = Treatment), 
            size = 1.5) +

  # Add confidence intervals
  geom_ribbon(data = boot_conf_preds_grouped, aes(x = Body_temp, ymin = conf_lower, ymax = conf_upper, 
                                                  fill = Treatment), 
              alpha = 0.2, inherit.aes = FALSE) +

  scale_color_manual(values = c("darkblue", "darkred", "lightblue", "darkgreen", 
                                "purple", "orange", "brown", "pink")) +  
  scale_fill_manual(values = c("darkblue", "darkred", "lightblue", "darkgreen", 
                               "purple", "orange", "brown", "pink")) +  
  scale_shape_manual(values = c(16, 17, 18, 19, 15, 7, 8, 10)) +  

  theme_bw() +
  ylim(-0.5, 4) +
  theme_classic() +
  labs(x = "Temperature (°C)", 
       y = "Maximum Sprint Speed 0.25m (m/s)", 
       color = "Treatment", 
       shape = "Treatment", 
       fill = "Treatment")

TPC_boatman_treat

```

```{r}
ggsave("~/Desktop/phd/Documents/Chapter_1_Honours/TELO.tiff", TPC_boatman_treat, width = 7.5, height = 4, dpi = 300)
```








```{r}
SPRINT <- ggplot(combined_data, aes(x =Tgape, y = topt)) +
  geom_point(size = 3, alpha = 0.7) +
  geom_smooth(method = "lm", se = 0.2, color = "black") +    
  labs(title = "(f)") +
  xlab("P80 (°C)") +
  ylab("Rmax (m/s)") +
  theme_classic() +
  #facet_wrap(~Pop)+
  scale_color_manual(values = c("blue", "red", "green", "orange"))  # Adjust colors as needed

SPRINT

```

```{r}
ggsave("~/Desktop/phd/Documents/Chapter_1_Honours/TELO.tiff", SPRINT, width = 7.5, height = 4, dpi = 300)
```






```{r}

d_params$Pop <- factor(d_params$Pop, levels = c("STURT", "MR", "KNGA", "NGKT"))
d_params$Treatment <- factor(d_params$Treatment, levels = c("Warm", "Cool"))
```


```{r}
Toptgraph <- ggplot(d_params, aes(x = Pop, y = topt, colour = interaction(Pop, Treatment), fill = interaction(Pop, Treatment))) + 
  geom_boxplot(outlier.shape = NA, colour = "black", alpha = 1) + 
  geom_point(position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.75), size = 1, alpha = 0.5, colour = "black") + 
    scale_fill_manual(
    values = c(
    "STURT.Warm" = "#9E2A2F",  # Dark Red for Warm, Sturt
    "STURT.Cool" = "#003366",  # Dark Blue for Cool, Sturt
    "MR.Warm" = "#E31A1C",     # Red for Warm, MR
    "MR.Cool" = "#4A90E2",     # Blue for Cool, MR
    "KNGA.Warm" = "#D44B2D",   # Red for Warm, KNGA
    "KNGA.Cool" = "#1F77B4",   # Blue for Cool, KNGA
    "NGKT.Warm" = "#FF6F61",   # Light Red for Warm, NGKT
    "NGKT.Cool" = "#56B4D3"    # Light Blue for Cool, NGKT
  )) +
  scale_colour_manual(
    values = c(
    "STURT.Warm" = "#9E2A2F",  # Dark Red for Warm, Sturt
    "STURT.Cool" = "#003366",  # Dark Blue for Cool, Sturt
    "MR.Warm" = "#E31A1C",     # Red for Warm, MR
    "MR.Cool" = "#4A90E2",     # Blue for Cool, MR
    "KNGA.Warm" = "#D44B2D",   # Red for Warm, KNGA
    "KNGA.Cool" = "#1F77B4",   # Blue for Cool, KNGA
    "NGKT.Warm" = "#FF6F61",   # Light Red for Warm, NGKT
    "NGKT.Cool" = "#56B4D3"    # Light Blue for Cool, NGKT
  )) +  # Customize point colors for all combinations
  scale_x_discrete(labels = c("KNGA" = "Kinchega National Park", "MR" = "Muloorina Station", "NGKT" = "Ngarkat CP", "STURT" = "Sturt National Park")) +
  labs(x = "", y = "Topt (\u00B0C)") +

  
  
  theme_classic() +
  ylim(30, 42.7) +
  theme(legend.position = "none")

Toptgraph

```

```{r}
library(ggplot2)
library(dplyr)

# Summarize data to get mean and SE for each group
d_summary <- d_params %>%
  group_by(Treatment) %>%
  summarise(
    mean_topt = mean(topt, na.rm = TRUE),
    se_topt = sd(topt, na.rm = TRUE) / sqrt(n()),
    .groups = "drop"
  )
sig_labels <- data.frame(
  Treatment = c( "Cool", "Warm"),
  mean_topt = d_summary$mean_topt + 6,  # Adjust height above bars
  label = c("a", "b")  # Assign letters
)
# Ensure factor levels are ordered correctly
#d_summary$Pop <- factor(d_summary$Pop, levels = c("STURT", "MR", "NGKT", "KNGA"))
d_summary$Treatment <- factor(d_summary$Treatment, levels = c("Warm", "Cool"))

# Create a bar graph with jittered points
Toptgraph <- ggplot(d_summary, aes(x = Treatment, y = mean_topt, fill = Treatment)) + 
  # Bar plot with mean values
  geom_bar(stat = "identity", position = position_dodge(width = 0.75), aplha=0.9, colour = "black", width = 0.7) +  # Bars with dodging
  geom_errorbar(aes(ymin = mean_topt - se_topt, ymax = mean_topt + se_topt), 
                width = 0.2, size = 1, position = position_dodge(width = 0.75)) +  # Error bars
  
  # Jittered points for individual observations
  geom_jitter(data = d_params, aes(x =  Treatment, y = topt), 
              position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.75), 
              size = 2, alpha = 0.5, colour = "black") +  # Jittered points

  scale_fill_manual(
    values = c(
    "Warm" = "#9E2A2F",
    "Cool" = "#4A90E2"))+
    scale_colour_manual(
    values = c(
    "Warm" = "#9E2A2F",
    "Cool" = "#4A90E2"))+

  # Adjust the y-axis limits using coord_cartesian
  coord_cartesian(ylim = c(30, 42.7)) +  # Adjust the view without removing data
  
   geom_text(data = sig_labels, aes(x = Treatment, y = mean_topt, label = label), size = 6, vjust = 0) +  
  # Add labels and theme
  
  labs(x = "", y = "Topt (°C)") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Slant x-axis labels

# Print the plot
Toptgraph


```

```{r}
ggsave("~/Desktop/phd/Documents/Chapter_1_Honours/TELO.tiff", Toptgraph, width = 7.5, height = 4, dpi = 300)
```





```{r}
library(ggplot2)
library(dplyr)

# Summarize data to get mean and SE for each group
d_summary <- d_params %>%
  group_by(Treatment) %>%
  summarise(
    mean_rmax = mean(rmax, na.rm = TRUE),
    se_rmax = sd(rmax, na.rm = TRUE) / sqrt(n()),
    .groups = "drop"
  )
sig_labels <- data.frame(
  Treatment = c( "Cool", "Warm"),
  mean_rmax = d_summary$mean_rmax + 1.3,  # Adjust height above bars
  label = c("a", "b")  # Assign letters
)
# Ensure factor levels are ordered correctly
#d_summary$Pop <- factor(d_summary$Pop, levels = c("STURT", "MR", "NGKT", "KNGA"))
d_summary$Treatment <- factor(d_summary$Treatment, levels = c("Warm", "Cool"))

# Create a bar graph with jittered points
rmaxgraph <- ggplot(d_summary, aes(x = Treatment, y = mean_rmax, fill = Treatment)) + 
  # Bar plot with mean values
  geom_bar(stat = "identity", position = position_dodge(width = 0.75), aplha=0.9, colour = "black", width = 0.7) +  # Bars with dodging
  geom_errorbar(aes(ymin = mean_rmax - se_rmax, ymax = mean_rmax + se_rmax), 
                width = 0.2, size = 1, position = position_dodge(width = 0.75)) +  # Error bars
  
  # Jittered points for individual observations
  geom_jitter(data = d_params, aes(x =  Treatment, y = rmax), 
              position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.75), 
              size = 2, alpha = 0.5, colour = "black") +  # Jittered points

  geom_text(data = sig_labels, aes(x = Treatment, y = mean_rmax, label = label), size = 6, vjust = 0) +  
  scale_fill_manual(
    values = c(
    "Warm" = "#9E2A2F",
    "Cool" = "#4A90E2"))+
    scale_colour_manual(
    values = c(
    "Warm" = "#9E2A2F",
    "Cool" = "#4A90E2"))+

  # Adjust the y-axis limits using coord_cartesian
  coord_cartesian(ylim = c(1.5, 4)) +  # Adjust the view without removing data
  
  # Add labels and theme
  labs(x = "", y = "Rmax (m/s)") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Slant x-axis labels

# Print the plot
rmaxgraph


```



```{r}
ggsave("~/Desktop/phd/Documents/Chapter_1_Honours/TELO.tiff", rmaxgraph, width = 7.5, height = 4, dpi = 300)
```



```{r}
library(ggplot2)
library(dplyr)

# Summarize data to get mean and SE for each group
d_summary <- d_params %>%
  group_by(Treatment) %>%
  summarise(
    mean_breadth = mean(breadth, na.rm = TRUE),
    se_breadth = sd(breadth, na.rm = TRUE) / sqrt(n()),
    .groups = "drop"
  )
sig_labels <- data.frame(
  Treatment = c( "Cool", "Warm"),
  mean_breadth = d_summary$mean_breadth + 5,  # Adjust height above bars
  label = c("b", "a")  # Assign letters
)
# Ensure factor levels are ordered correctly
#d_summary$Pop <- factor(d_summary$Pop, levels = c("STURT", "MR", "NGKT", "KNGA"))
d_summary$Treatment <- factor(d_summary$Treatment, levels = c("Warm", "Cool"))

# Create a bar graph with jittered points
breadthgraph <- ggplot(d_summary, aes(x = Treatment, y = mean_breadth, fill = Treatment)) + 
  # Bar plot with mean values
  geom_bar(stat = "identity", position = position_dodge(width = 0.75), aplha=0.9, colour = "black", width = 0.7) +  # Bars with dodging
  geom_errorbar(aes(ymin = mean_breadth - se_breadth, ymax = mean_breadth + se_breadth), 
                width = 0.2, size = 1, position = position_dodge(width = 0.75)) +  # Error bars
  
  # Jittered points for individual observations
  geom_jitter(data = d_params, aes(x =  Treatment, y = breadth), 
              position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.75), 
              size = 2, alpha = 0.5, colour = "black") +  # Jittered points

  scale_fill_manual(
    values = c(
    "Warm" = "#9E2A2F",
    "Cool" = "#4A90E2"))+
    scale_colour_manual(
    values = c(
    "Warm" = "#9E2A2F",
    "Cool" = "#4A90E2"))+

  # Adjust the y-axis limits using coord_cartesian
  coord_cartesian(ylim = c(6, 16)) +  # Adjust the view without removing data
  geom_text(data = sig_labels, aes(x = Treatment, y = mean_breadth, label = label), size = 6, vjust = 0) + 
  # Add labels and theme
  labs(x = "", y = "P80 (°C)") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Slant x-axis labels

# Print the plot
breadthgraph


```




```{r}
ggsave("~/Desktop/phd/Documents/Chapter_1_Honours/TELO.tiff", breadthgraph, width = 7.5, height = 4, dpi = 300)
```






```{r}
## IMPORT DATA
pictus_CTMAX <- read_csv("~/Desktop/phd/Documents/Chapter 3/Datasheets/CTmax_DR_2024.csv")
pictus_CTMAX$Treatment <- as.factor(pictus_CTMAX$Treatment)
pictus_CTMAX$Pop <- as.factor(pictus_CTMAX$Pop)
pictus_CTMAX$Pop <- factor(pictus_CTMAX$Pop, levels = c("STURT", "MR", "KNGA", "NRKT"))
pictus_CTMAX$Treatment <- factor(pictus_CTMAX$Treatment, levels = c("Warm", "Cool"))
```







```{r}
library(ggplot2)
library(dplyr)

# Summarize data to get mean and SE for each group
d_summary <-pictus_CTMAX %>%
  group_by(Pop) %>%
  summarise(
    mean_Tgape = mean(Tgape, na.rm = TRUE),
    se_Tgape = sd(Tgape, na.rm = TRUE) / sqrt(n()),
    .groups = "drop"
  )

sig_labels <- data.frame(
  Pop = c("STURT", "MR", "KNGA", "NRKT"),
  mean_Tgape = d_summary$mean_Tgape + 2,  # Adjust height above bars
  label = c("a", "ab", "b", "ab")  # Assign letters
)

# Ensure factor levels are ordered correctly
d_summary$Pop <- factor(d_summary$Pop, levels = c("STURT", "MR", "NRKT", "KNGA"))
#d_summary$Treatment <- factor(d_summary$Treatment, levels = c("Warm", "Cool"))

# Create a bar graph with jittered points
Tgapegraph <- ggplot(d_summary, aes(x = Pop, y = mean_Tgape, fill = Pop)) + 
  # Bar plot with mean values
  geom_bar(stat = "identity", position = position_dodge(width = 0.75), aplha=0.9, colour = "black", width = 0.7) +  # Bars with dodging
  geom_errorbar(aes(ymin = mean_Tgape - se_Tgape, ymax = mean_Tgape + se_Tgape), 
                width = 0.2, size = 1, position = position_dodge(width = 0.75)) +  # Error bars
  
  # Jittered points for individual observations
  geom_jitter(data = pictus_CTMAX, aes(x =  Pop, y = Tgape), 
              position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.75), 
              size = 2, alpha = 0.5, colour = "black") +  # Jittered points

  scale_fill_manual(
    values = c(
    "STURT" = "#9E2A2F",  
    "MR" = "#E31A1C",     
    "KNGA" = "#1F77B4",   
   
    "NRKT" = "#56B4D3"))+ 
 
    scale_colour_manual(
    values = c(
    "STURT" = "#9E2A2F",  
    "MR" = "#E31A1C",     
    "KNGA" = "#1F77B4",   
   
    "NRKT" = "#56B4D3"))+

  # Adjust the y-axis limits using coord_cartesian
  coord_cartesian(ylim = c(41, 45.3)) +  # Adjust the view without removing data
  
  geom_text(data = sig_labels, aes(x = Pop, y = mean_Tgape, label = label), size = 6, vjust = 0) +  # Add significance letters
  # Add labels and theme
  scale_x_discrete(labels = c("KNGA" = "Kinchega National Park", "MR" = "Muloorina Station", "NRKT" = "Ngarkat CP", "STURT" = "Sturt National Park")) +
  labs(x = "", y = "Tgape (°C)") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Slant x-axis labels

# Print the plot
Tgapegraph

```

```{r}
ggsave("~/Desktop/phd/Documents/Chapter_1_Honours/TELO.tiff", Tgapegraph, width = 7.5, height = 4, dpi = 300)
```


```{r}
library(ggplot2)
library(dplyr)

# Summarize data to get mean and SE for each group
d_summary <-pictus_CTMAX %>%
  group_by(Pop) %>%
  summarise(
    mean_Vtmax = mean(Vtmax, na.rm = TRUE),
    se_Vtmax = sd(Vtmax, na.rm = TRUE) / sqrt(n()),
    .groups = "drop"
  )

sig_labels <- data.frame(
  Pop = c("STURT", "MR", "KNGA", "NRKT"),
  mean_Vtmax = d_summary$mean_Vtmax + 4.2,  # Adjust height above bars
  label = c("a", "b", "b", "b")  # Assign letters
)

# Ensure factor levels are ordered correctly
d_summary$Pop <- factor(d_summary$Pop, levels = c("STURT", "MR", "NRKT", "KNGA"))
#d_summary$Treatment <- factor(d_summary$Treatment, levels = c("Warm", "Cool"))

# Create a bar graph with jittered points
Vtmaxgraph <- ggplot(d_summary, aes(x = Pop, y = mean_Vtmax, fill = Pop)) + 
  # Bar plot with mean values
  geom_bar(stat = "identity", position = position_dodge(width = 0.75), aplha=0.9, colour = "black", width = 0.7) +  # Bars with dodging
  geom_errorbar(aes(ymin = mean_Vtmax - se_Vtmax, ymax = mean_Vtmax + se_Vtmax), 
                width = 0.2, size = 1, position = position_dodge(width = 0.75)) +  # Error bars
  
  # Jittered points for individual observations
  geom_jitter(data = pictus_CTMAX, aes(x =  Pop, y = Vtmax), 
              position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.75), 
              size = 2, alpha = 0.5, colour = "black") +  # Jittered points

  scale_fill_manual(
    values = c(
    "STURT" = "#9E2A2F",  
    "MR" = "#E31A1C",     
    "KNGA" = "#1F77B4",   
   
    "NRKT" = "#56B4D3"))+ 
 
    scale_colour_manual(
    values = c(
    "STURT" = "#9E2A2F",  
    "MR" = "#E31A1C",     
    "KNGA" = "#1F77B4",   
   
    "NRKT" = "#56B4D3"))+

  # Adjust the y-axis limits using coord_cartesian
  coord_cartesian(ylim = c(36, 45.3)) +  # Adjust the view without removing data
  
  geom_text(data = sig_labels, aes(x = Pop, y = mean_Vtmax, label = label), size = 6, vjust = 0) +  # Add significance letters
  # Add labels and theme
  labs(x = "", y = "Vtmax (°C)") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Slant x-axis labels

# Print the plot
Vtmaxgraph

```




```{r}
ggsave("~/Desktop/phd/Documents/Chapter_1_Honours/TELO.tiff", Vtmaxgraph, width = 7.5, height = 4, dpi = 300)
```


```{r}
library(ggplot2)
library(dplyr)

# Summarize data to get mean and SE for each group
d_summary <-pictus_CTMAX %>%
  group_by(Clade) %>%
  summarise(
    mean_Ctmin = mean(Ctmin, na.rm = TRUE),
    se_Ctmin = sd(Ctmin, na.rm = TRUE) / sqrt(n()),
    .groups = "drop"
  )

sig_labels <- data.frame(
  Clade = c("North", "South"),
  mean_Ctmin = d_summary$mean_Ctmin + 4.2,  # Adjust height above bars
  label = c("b", "a")  # Assign letters
)

# Ensure factor levels are ordered correctly
d_summary$Clade <- factor(d_summary$Clade, levels = c("North", "South"))
#d_summary$Treatment <- factor(d_summary$Treatment, levels = c("Warm", "Cool"))

# Create a bar graph with jittered points
Ctmingraph <- ggplot(d_summary, aes(x = Clade, y = mean_Ctmin, fill = Clade)) + 
  # Bar plot with mean values
  geom_bar(stat = "identity", position = position_dodge(width = 0.75), aplha=0.9, colour = "black", width = 0.7) +  # Bars with dodging
  geom_errorbar(aes(ymin = mean_Ctmin - se_Ctmin, ymax = mean_Ctmin + se_Ctmin), 
                width = 0.2, size = 1, position = position_dodge(width = 0.75)) +  # Error bars
  
  # Jittered points for individual observations
  geom_jitter(data = pictus_CTMAX, aes(x =  Clade, y = Ctmin), 
              position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.75), 
              size = 2, alpha = 0.5, colour = "black") +  # Jittered points

  scale_fill_manual(
    values = c(
    "South" = "#1F77B4",  
    "North" = "#9E2A2F"))+ 
 
    scale_colour_manual(
    values = c(
    "South" = "#1F77B4",  
    "North" = "#9E2A2F"))+

  # Adjust the y-axis limits using coord_cartesian
 coord_cartesian(ylim = c(5, 13)) +  # Adjust the view without removing data
  
  geom_text(data = sig_labels, aes(x = Clade, y = mean_Ctmin, label = label), size = 6, vjust = 0) +  # Add significance letters
  # Add labels and theme
  labs(x = "", y = "Ctmin (°C)") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Slant x-axis labels

# Print the plot
Ctmingraph

```

```{r}
ggsave("~/Desktop/phd/Documents/Chapter_1_Honours/TELO.tiff", Ctmingraph, width = 7.5, height = 4, dpi = 300)
```






```{r}
library(gridExtra)
thermal.figure <- grid.arrange(Tgapegraph , CTmingraph, Vtmaxgraph, Toptgraph, RMAXgraph, breadthgraph, ncol= 2)
```


```{r}
view(thermal.figure)
```


```{r}
thermal.figure <- ggpubr::ggarrange( Tgapegraph ,Vtmaxgraph,Ctmingraph,Toptgraph, rmaxgraph, breadthgraph,
                                         ncol = 3, nrow = 2,
                                         widths = c(10, 10),
                                         heights = c(10, 10))  +
  annotate("text", x = c(0.024, 0.35, 0.67, 0.024, 0.35, 0.67), y = c(0.98, 0.98, 0.98,0.55, 0.55, 0.55), label = c("A)", "B)", "C)", "D)", "E)", "F)"),
           size = 4, fontface = "bold")

thermal.figure 

```


```{r}
ggsave("~/Desktop/phd/Documents/Chapter_1_Honours/TELO.tiff", thermal.figure, width = 11.25, height = 6, dpi = 300)
```





